export const RECEIVE_USERS = 'RECEIVE_USERS';
export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';